apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-cicd
  name: test-cicd
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-cicd
status:
  loadBalancer: {}